mybatis:
  mapper-locations: classpath*:/mybatis.mapper/*Mapper.xml
  type-aliases-package: com.admin.mybatis.domain
  #开启MyBatis的二级缓存
  configuration:
    cache-enabled: true
mapper:
  mappers:
    - com.admin.mybatis.util.BaseMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: false
  support-methods-arguments: true
